### ISSUE TITLE
Korean letters dont join

### ISSUE THREAD

**Issue by fariskas** [nhnent/tui.component.virtual-keyboard#1]
Currently when i press korean keys on the keyboard, they just input single korean letters.

Example: ㅅㅏㄹㅏㅇ.

Can it be instead like this? : 사랑

**Comment by seonim-ryu** [comment]
@fariskas 
Thanks for using our component.
The TUI Virtual Keyboard component was designed to create randomized character used in places such as online banking.
So the Korean letters can not be combined.
